version: '3'

services: 
    web:
        build: 
            context: .
            dockerfile: docker/nginx/Dockerfile
        ports: 
            - "8080:80"
        volumes: 
            - ./20210909ditanshequ/public/:/app/
        links: 
            - php

    php:
        build: 
            context: .
            dockerfile: docker/php/Dockerfile

        volumes: 
             - ./20210909ditanshequ/public/:/app/
